//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCController.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ThreeByteIntermedia\\PCManager\\Settings\\appsettings.json")]
        public string AppSettingsFile {
            get {
                return ((string)(this["AppSettingsFile"]));
            }
            set {
                this["AppSettingsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=C:\\ThreeByteIntermedia\\PCManager\\Logs\\log.db;Version=3;Read Only=True" +
            ";")]
        public string ConnectionStringLogs {
            get {
                return ((string)(this["ConnectionStringLogs"]));
            }
            set {
                this["ConnectionStringLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=C:\\ThreeByteIntermedia\\PCManager\\Logs\\network.db;Version=3;")]
        public string ConnectionStringNetwork {
            get {
                return ((string)(this["ConnectionStringNetwork"]));
            }
            set {
                this["ConnectionStringNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ThreeByteIntermedia\\PCManager\\Settings\\")]
        public string LocalDataFolder {
            get {
                return ((string)(this["LocalDataFolder"]));
            }
            set {
                this["LocalDataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ThreeByteIntermedia\\PCManager\\Settings\\appsettings.json")]
        public string LocalDataFolderFile {
            get {
                return ((string)(this["LocalDataFolderFile"]));
            }
            set {
                this["LocalDataFolderFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ThreeByteIntermedia\\PCManager\\Logs\\log.db")]
        public string SQLiteDBPath {
            get {
                return ((string)(this["SQLiteDBPath"]));
            }
            set {
                this["SQLiteDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ThreeByteIntermedia\\PCManager\\Logs\\PCControllerLogs.json")]
        public string LocalLogFolderFile {
            get {
                return ((string)(this["LocalLogFolderFile"]));
            }
            set {
                this["LocalLogFolderFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16009")]
        public int PCListenerUDPPort {
            get {
                return ((int)(this["PCListenerUDPPort"]));
            }
            set {
                this["PCListenerUDPPort"] = value;
            }
        }
    }
}
